# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
archives:
- replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
- github:
    owner: peijiinsg
    name: homebrew-tap
  commit_author:
    name: peijiinsg
    email: peiji@gmail.com
  url_template: "https://github.com/peijiinsg/playground/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
  custom_require: "../custom_download_strategy"
  download_strategy: GitHubPrivateRepositoryReleaseDownloadStrategy
  homepage:  https://github.com/peijiinsg/playground
  description: Useful toolset
  folder: Formula
  test: |
      system "#{bin}/playground help"
  install: |
      system("tar -xvf playground")

